service: aws-python-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: somecuteanimals2
          event: s3:ObjectCreated:*
      - sns: arn:aws:sns:ap-northeast-1:255945442255:somecuteanimals1